# algorithm for getting crowding level on platforms

## turnstile data module
will just be imported in final product. here for easy access in dev

In [1]:
#from .sort_by_week_day import sort_all_days

In [1]:
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 26 17:46:35 2020

@author: Wenqing Zhong
"""
import csv
import datetime
'''
  first use CSV_DATA.py to get data for one station, than use 'sort_all_days' to sort data by week day
  input:station name
  output: 7 csv files, each file includes data for one week day
'''
def get_week_days(stationname):
    
    name="DATE"
    position=-1
    date=[]
    week=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
    days={}
    
    
    with open('%s.csv'%stationname,'r') as stationfile:
        reader = csv.reader(stationfile) 
        head=next(reader)       
        for item in head:
            position=position+1
            if name in item:
                break
        #find which column stores date         
        for row in reader:
            date.append(datetime.datetime.strptime(row[position], '%m/%d/%Y').strftime("%a"))
            #change dates to week days
        stationfile.seek(0)
                                    
        for i in range(len(week)):
            for j in range(len(date)):
                if(date[j] == week[i]):
                    try:
                        days[week[i]].append(j+2)
                    except KeyError:
                        days[week[i]] = [j+2]                        
        return days   
     #'days' is a dictionary with week days as keys and csv line numbers as values

def sort_one_day(stationname,days,k):
    #create a csv file for one week day
      keys= list(days.keys())
      with open('%s.csv'%stationname,'r') as stationfile:
        reader = csv.reader(stationfile) 
        head=next(reader)
        count=0
        with open('%s.csv'%keys[k], 'w',newline='') as csvfile:
                writer = csv.writer(csvfile,quoting=csv.QUOTE_NONE)
                writer.writerow(head)
                c=days.get(keys[k])
                for row in reader:
                    count=count+1
                    if(count in c):
                        try:
                            writer.writerow(row)
                        except:
                            return False               
        stationfile.seek(0)  
      return
 
def sort_all_days(stationname):
    #create csv files for all week days
    days=get_week_days(stationname)
    for i in range(len(list(days.keys()))):
        sort_one_day(stationname,days,i)    
    return
      
sort_all_days("96 ST")

#puts the last week into monday,tues, etc files in the shared directory

**USE CAL_ENTRIES_EXITS_IN_4H_CHUNKS**

reference used for below: https://pythontic.com/datetime/date/weekday

## for building algorithm file

In [24]:
"""
@author: Mehr Kaur
"""
from datetime import datetime

In [25]:
today = datetime.date(datetime.now())

In [26]:
todayDay = today.weekday()
weekDays = ("Mon","Tue","Wed","Thu","Fri","Sat","Sun")
fileName = weekDays[todayDay] + ".csv"
print(fileName) #the name of the file for the day of the week, last week

Sun.csv

In [27]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv(fileName, sep=',') #read file and make data accessible to program
df

,Unnamed: 0,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,48685,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,04:00:00,REGULAR,2896722,1013459
1,48686,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,08:00:00,REGULAR,2896730,1013467
2,48687,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,12:00:00,REGULAR,2896745,1013477
3,48688,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,16:00:00,REGULAR,2896792,1013495
4,48689,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,20:00:00,REGULAR,2896826,1013513
...,...,...,...,...,...,...,...,...,...,...,...,...
661,166399,R251,R144,00-03-02,96 ST,6,IRT,06/14/2020,09:00:00,REGULAR,645949150,263300
662,166400,R251,R144,00-03-02,96 ST,6,IRT,06/14/2020,13:00:00,REGULAR,645949202,263343
663,166401,R251,R144,00-03-02,96 ST,6,IRT,06/14/2020,17:00:00,REGULAR,645949323,263400
664,166402,R251,R144,00-03-02,96 ST,6,IRT,06/14/2020,21:00:00,REGULAR,645949446,263435
665,166403,R251,R144,00-03-02,96 ST,6,IRT,06/15/2020,01:00:00,REGULAR,645949499,263465

**note: i think sort_by_week_day might have a bug because its showing many different dates**

In [31]:
#THIS PART IS TEMP, just until we can get 1 day in 1 file
june28 = df[df["DATE"] == "06/28/2020"]
df = june28
df

,Unnamed: 0,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,48685,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,04:00:00,REGULAR,2896722,1013459
1,48686,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,08:00:00,REGULAR,2896730,1013467
2,48687,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,12:00:00,REGULAR,2896745,1013477
3,48688,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,16:00:00,REGULAR,2896792,1013495
4,48689,N039,R251,01-00-00,96 ST,BC,IND,06/28/2020,20:00:00,REGULAR,2896826,1013513
...,...,...,...,...,...,...,...,...,...,...,...,...
216,168316,R251,R144,00-03-02,96 ST,6,IRT,06/28/2020,05:00:00,REGULAR,645965398,268563
217,168317,R251,R144,00-03-02,96 ST,6,IRT,06/28/2020,09:00:00,REGULAR,645965463,268615
218,168318,R251,R144,00-03-02,96 ST,6,IRT,06/28/2020,13:00:00,REGULAR,645965552,268667
219,168319,R251,R144,00-03-02,96 ST,6,IRT,06/28/2020,17:00:00,REGULAR,645965698,268730
220,168320,R251,R144,00-03-02,96 ST,6,IRT,06/28/2020,21:00:00,REGULAR,645965846,268763

In [ ]:
dfEntries = df['ENTRIES'].sum() #will change to sum from 4 hr incr value

In [32]:
#total entries / minutes in a time segment (this should definitely be refined as we progress)
avgPerMinTotal = dfEntries / 240

In [33]:
print(avgPerMinTotal) #this still seems ridiculously huge. might be a bug somewhere or missing subtracting some elements

3235210.673611111

**my thinking is we need to make a table of each station and how many platforms it has, and program looks up the value based on user needs. this approach is also rudimentary and can be refined**

96th street has 2 in service island platforms https://en.wikipedia.org/wiki/96th_Street_station_(IRT_Broadway%E2%80%93Seventh_Avenue_Line) using that value for now

In [34]:
#addPerMin = avgPerMinTotal /2
addPerMin = avgPerMinTotal

**need working train arrival module to use here.**

info needed asap (for rudimentary algo to be finished): when the last train 
- arrival time of the latest train from each line that the station services
    - associate lines with platforms using above mentioned reference table

assumptions made below: 
- each platform services 1 line
- all passengers get on the train when it comes and the platform is empty.
- negligable time to get from turnstiles to platform after entry

In [35]:
#today variable defined earlier
#x represents arrival datetime of last train to that station
'''temp = today - x  
diffInMin = temp.seconds / 60'''
#until we have real time file, make up value

diffInMin = 3 #average spacing between trains
popOnPlatform = diffInMin * addPerMin #the peak amount right before the next train comes in

**need some sort of grading system. what counts as "red" level crowd vs "green" level? Mysore reccommended talking to MTA workers to figure out where these thresholds are.**
for now, using made-up values


andrew's idea:
write another module to do this--

make an int called largePop (from pre-covid crowd levels). processed same way as popOnPlatform
 
 - largePop = largeAvgPerMinTotal * diffInMin (same train spacing, just with max precovid crowds).
     - this causes diffInMin to cancel, so we arent using any train arrival data
 - alternatively: use previous train spacing --> we dont have this data stored
 
0 <= popOnPlatform / largePop <= 1
which can be converted to a color with matplot lib or the visualizer

In [36]:

if(popOnPlatform <= 100):
    print("GREEN")
elif (popOnPlatform <= 200):
    print("YELLOW")
else:
    print("RED")

RED

**color indications above can be returned to gui on client-side**

In [ ]:
STATION_CSV_DATA
get final station data to get 1 day 1 station
julian modified this more to really isolate one single station